version: '3'
services:
  postgres:
    image: postgres
    container_name: ms-hoja-servicio
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root